title: Node Exporter disk I/O metrics
type: metrics
streams:
  - input: prometheus/metrics
    vars:
      - name: period
        type: text
        title: Period
        required: true
        show_user: true
        default: 60s
      - name: tags
        type: text
        title: Tags
        multi: true
        required: false
        show_user: false
        default:
          - prometheus-node-exporter-diskstats
      - name: use_types
        type: bool
        title: Use Types
        required: true
        show_user: false
        default: true
      - name: rate_counters
        type: bool
        title: Rate Counters
        required: true
        show_user: false
        default: true
      - name: processors
        type: yaml
        title: Processors
        required: false
        show_user: false
    title: Node Exporter disk I/O metrics
    description: Collect per-device disk I/O metrics from node_exporter
elasticsearch:
  index_mode: time_series
