- name: proxmox
  type: group
  fields:
    - name: task
      type: group
      fields:
        - name: node
          type: keyword
          description: Node that ran the task.
        - name: type
          type: keyword
          description: Task type (vzdump, qmstart, qmstop, vncproxy, etc).
        - name: vmid
          type: keyword
          description: Target VM or container ID.
        - name: upid
          type: keyword
          description: Unique Process ID (UPID) string.
        - name: duration_seconds
          type: long
          description: Task duration in seconds.
